### ISSUE TITLE
There are multiple unhandled promise rejection shown in tests

### ISSUE THREAD

**Issue by fguitton** [dsi-icl/optimise-core#37]
Tests are showing multiple unhandled promises like the following one.
These suggest certain things are not done in the right order in the code

```
  console.warn node_modules/bluebird/js/release/debuggability.js:873
    Unhandled rejection Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
        at ServerResponse.setHeader (_http_outgoing.js:471:11)
        at ServerResponse.header (C:\Repos\optimise-core\node_modules\express\lib\response.js:767:10)
        at ServerResponse.send (C:\Repos\optimise-core\node_modules\express\lib\response.js:170:12)
        at knex.select.where.then.resu (C:\Repos\optimise-core\src\controllers\demographicDataController.js:57:45)
        at tryCatcher (C:\Repos\optimise-core\node_modules\bluebird\js\release\util.js:16:23)
        at Promise._settlePromiseFromHandler (C:\Repos\optimise-core\node_modules\bluebird\js\release\promise.js:512:31)
        at Promise._settlePromise (C:\Repos\optimise-core\node_modules\bluebird\js\release\promise.js:569:18)
        at Promise._settlePromise0 (C:\Repos\optimise-core\node_modules\bluebird\js\release\promise.js:614:10)
        at Promise._settlePromises (C:\Repos\optimise-core\node_modules\bluebird\js\release\promise.js:693:18)
        at Async.Object.<anonymous>.Async._drainQueue (C:\Repos\optimise-core\node_modules\bluebird\js\release\async.js:133:16)
```

**Comment by Radiateurs** [comment]
This one was already fixed. Something must have happen on the repository that changed the file. Like a bad commit merge.
Anyway this fixed in commit 2c7d9310d273dd6d46306865461728b81774daa1

**Comment by Radiateurs** [comment]
[Update] Partially fixed in 661718596db73a9575a8f5f9eefd47e90fa958fc
Still working on it

**Comment by fguitton** [comment]
@sou-c This is not resolved.
The following line has to be reconsidered once the problem is resolved.

https://github.com/dsi-icl/optimise-core/blob/348fc75ee968211d4d075e9d709cbe94f6c2b617/src/utils/db-handler.js#L44
